export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const url = process.env.KV_REST_API_URL;
  const token = process.env.KV_REST_API_TOKEN;
  const resendKey = process.env.RESEND_API_KEY;

  if (!url || !token || !resendKey) return res.status(500).json({ error: 'Missing config' });

  const snapRes = await fetch(`${url}/get/snapshots`, {
    headers: { Authorization: `Bearer ${token}` }
  });
  const snapData = await snapRes.json();
  let snapshots = [];
  if (snapData.result) {
    let val = snapData.result;
    while (typeof val === 'string') { try { val = JSON.parse(val); } catch(e) { break; } }
    if (Array.isArray(val) && val.length === 1 && typeof val[0] === 'string') { try { val = JSON.parse(val[0]); } catch(e) {} }
    if (Array.isArray(val)) snapshots = val;
  }

  if (!snapshots.length) return res.status(400).json({ error: 'No snapshots to report on' });

  const latest = snapshots[snapshots.length - 1];
  const prev = snapshots.length > 1 ? snapshots[snapshots.length - 2] : null;

  const fmt = (n) => {
    if (n == null) return '—';
    if (n >= 1000000) return (n/1000000).toFixed(2) + 'M';
    if (n >= 1000) return (n/1000).toFixed(1) + 'K';
    return Number(n).toLocaleString();
  };

  const withGrowth = latest.data.map(d => {
    const pe = prev ? prev.data.find(p => p.handle === d.handle) : null;
    const diff = pe ? d.followers - pe.followers : null;
    const pct = pe ? ((d.followers - pe.followers) / pe.followers * 100) : null;
    return { ...d, diff, pct };
  }).sort((a, b) => (b.diff ?? -Infinity) - (a.diff ?? -Infinity));

  const rows = withGrowth.map(d => {
    const growthStr = d.diff !== null ? `${d.diff >= 0 ? '+' : ''}${Number(d.diff).toLocaleString()}` : '—';
    const pctStr = d.pct !== null ? `${d.pct >= 0 ? '+' : ''}${d.pct.toFixed(2)}%` : '—';
    const color = d.diff > 0 ? '#27ae60' : d.diff < 0 ? '#c0392b' : '#888';
    return `<tr>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;"><a href="https://www.instagram.com/${d.handle}/" style="color:#1a1a1a;text-decoration:none;">@${d.handle}</a></td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;font-weight:600;">${fmt(d.followers)}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;color:${color};">${growthStr}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;color:${color};">${pctStr}</td>
    </tr>`;
  }).join('');

  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:600px;margin:0 auto;padding:2rem;">
      <div style="text-align:center;margin-bottom:2rem;">
        <a href="https://ig-follower-proxy.vercel.app" style="display:inline-block;background:#1a1a1a;color:#fff;font-size:13px;font-weight:500;padding:10px 24px;border-radius:8px;text-decoration:none;letter-spacing:0.03em;">View Live Dashboard →</a>
      </div>
      <h1 style="font-size:20px;font-weight:600;margin-bottom:4px;">Instagram Weekly Report</h1>
      <p style="font-size:13px;color:#888;margin-bottom:1.5rem;">Alamo Records / Santa Anna Roster — ${latest.date}</p>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f9f9f7;">
            <th style="text-align:left;padding:8px 12px;font-size:12px;color:#888;font-weight:500;border-bottom:2px solid #eee;">Handle</th>
            <th style="text-align:left;padding:8px 12px;font-size:12px;color:#888;font-weight:500;border-bottom:2px solid #eee;">Followers</th>
            <th style="text-align:left;padding:8px 12px;font-size:12px;color:#888;font-weight:500;border-bottom:2px solid #eee;">Growth</th>
            <th style="text-align:left;padding:8px 12px;font-size:12px;color:#888;font-weight:500;border-bottom:2px solid #eee;">Growth %</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="font-size:12px;color:#aaa;margin-top:1.5rem;text-align:center;">Auto-generated by Alamo IG Tracker</p>
    </div>`;

  const emailRes = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: 'Alamo IG Tracker <onboarding@resend.dev>',
      to: ['jacobpassickdigital@gmail.com'],
      subject: `Alamo IG Weekly Report — ${latest.date}`,
      html
    })
  });

  const emailData = await emailRes.json();
  if (emailRes.ok) return res.status(200).json({ ok: true });
  return res.status(500).json({ error: emailData.message || 'Email failed' });
}
